# ==============================================================================
# PERFIL: DESARROLLO
# ==============================================================================

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/predio_mijangos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: predio_user
    password: Predio2025!
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging más verboso en desarrollo
logging:
  level:
    root: DEBUG
    com.predio.mijangos: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Actuator expuesto completamente en dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# CORS permisivo para desarrollo local
app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
      - http://localhost:19006
      - http://127.0.0.1:19006