# ==============================================================================
# CONFIGURACIÓN BASE - Predio Mijangos API
# Versión: 1.0.0
# Última Actualización: Octubre 2025
# ==============================================================================

spring:
  application:
    name: predio-mijangos-api
  
  # ========== DATASOURCE ==========
  datasource:
    url: jdbc:mysql://localhost:3307/predio_mijangos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true
    username: ${DB_USERNAME:predio_user}
    password: ${DB_PASSWORD:Predio2025!}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # ========== JPA / HIBERNATE ==========
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none  # NUNCA usar create/update en producción
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  # ========== FLYWAY ==========
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    schemas: predio_mijangos
    default-schema: predio_mijangos
    out-of-order: false
    clean-disabled: true
    validate-on-migrate: true

# ========== SERVER ==========
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
  error:
    include-message: always
    include-stacktrace: never

# ========== SEGURIDAD JWT ==========
app:
  security:
    jwt:
      secret: ${JWT_SECRET:NtnSniM87XKR2cDLBB4L+vrRHRKBUausPzBAFFHu6VU=}
      expiration-minutes: 480  # 8 horas
      refresh-expiration-minutes: 10080  # 7 días

# ========== LOGGING ==========
logging:
  level:
    root: INFO
    com.predio.mijangos: DEBUG
    com.predio.mijangos.core.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/predio-mijangos.log
    max-size: 10MB
    max-history: 30

# ========== SPRINGDOC / SWAGGER ==========
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

# ========== ACTUATOR (Health Checks) ==========
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true